name: stack-lint-extra-deps
description: Install and run stack-lint-extra-deps

inputs:
  version:
    description: Version of the tool to install
    required: true
    default: 1.1.0.7
  arguments:
    description: Arguments to pass. Must be shell-escaped. Default is none.
    required: false

outputs: {}

runs:
  using: composite
  steps:
    - uses: pbrisbin/setup-tool-action@v1
      with:
        name: stack-lint-extra-deps
        version: ${{ inputs.version }}
        url: "https://github.com/freckle/{name}/releases/download/v{version}/{name}-{arch}-{os}.{ext}"
        subdir: "{name}"
        os-darwin: osx
        arch-x64: x86_64

    - shell: bash
      run: |
        stack-lint-extra-deps ${{ inputs.arguments }}
      env:
        LOG_COLOR: always
        LOG_CONCURRENCY: 1
