name: stack-lint-extra-deps
version: 1.1.0.5

extra-doc-files:
  - README.md
  - CHANGELOG.md

extra-source-files:
  - test/examples/lts-18.18.yaml

default-extensions:
  - DerivingStrategies
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - TypeApplications

dependencies:
  - base

library:
  source-dirs: src
  dependencies:
    - Blammo
    - Glob
    - aeson
    - bytestring
    - conduit
    - containers
    - errors
    - extra
    - html-conduit
    - http-conduit
    - http-types
    - lens
    - optparse-applicative
    - relude
    - text
    - typed-process
    - unliftio-core
    - unliftio
    - xml-conduit
    - yaml

executables:
  stack-lint-extra-deps:
    source-dirs: app
    main: Main.hs
    dependencies:
      - Blammo
      - stack-lint-extra-deps

tests:
  doctest:
    main: Main.hs
    source-dirs: doctest
    dependencies:
      - aeson
      - doctest
      - yaml

  hspec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - Blammo
      - bytestring
      - containers
      - file-embed
      - hspec
      - hspec-expectations-lifted
      - stack-lint-extra-deps
