name: stack-lint-extra-deps
version: 1.1.0.2

extra-doc-files:
  - README.md
  - CHANGELOG.md

extra-source-files:
  - test/examples/lts-18.18.yaml

default-extensions:
  - DerivingStrategies
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - TypeApplications

dependencies:
  - base
  - rio

library:
  source-dirs: src
  dependencies:
    - Glob
    - aeson
    - html-conduit
    - http-conduit
    - http-types
    - optparse-applicative
    - xml-conduit
    - yaml

executables:
  stack-lint-extra-deps:
    source-dirs: app
    main: Main.hs
    dependencies:
      - stack-lint-extra-deps

tests:
  doctest:
    main: Main.hs
    source-dirs: doctest
    dependencies:
      - aeson
      - doctest
      - yaml

  hspec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - hspec-expectations-lifted
      - stack-lint-extra-deps
