name: CI

on:
  pull_request:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: freckle/stack-action@v5
      - uses: ./
        with:
          arguments: --format gha --path test/examples/lts-18.18.yaml --no-exit
          executable: stack exec -- stack-lint-extra-deps
          no-install: true

  test-action:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - macOS-latest

      fail-fast: false

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          arguments: --path test/examples/lts-18.18.yaml --no-exit
