name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: freckle/stack-cache-action@v1
      - uses: freckle/stack-action@v3

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /tmp/cache/lsd
          key: ${{ runner.os }}-integration
      - uses: freckle/stack-cache-action@v1
      - run: |
          stack run --no-terminal lsd -- \
            --exclude "*/amazonka" \
            --no-exit \
            --cache-dir /tmp/cache/lsd \
            test/examples/lts-18.18.yaml || true
