name: CI

on:
  pull_request:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: freckle/stack-action@v4

  test-action:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          # - macOS-latest
          # - windows-latest

      fail-fast: false

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          arguments: --path test/examples/lts-18.18.yaml --no-exit
