name: Release executables

on:
  push:
    branches: main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: tag
        uses: freckle/haskell-tag-action@v1
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

  create-release:
    needs: tag
    if: needs.tag.outputs.tag
    runs-on: ubuntu-latest
    steps:
      - id: create-release
        uses: freckle/action-gh-release@v2
        with:
          tag_name: ${{ needs.tag.outputs.tag }}
          generate_release_notes: true
          draft: true
    outputs:
      release_id: ${{ steps.create-release.outputs.id }}

  upload-assets:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            suffix: x86_64-linux
          - os: macOS-latest
            suffix: x86_64-osx

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: freckle/stack-cache-action@v2
      - run: |
          mkdir -p dist/stack-lint-extra-deps
          stack build --copy-bins --local-bin-path dist/stack-lint-extra-deps
          tar -C dist -czf ./stack-lint-extra-deps-${{ matrix.suffix }}.tar.gz ./stack-lint-extra-deps
      - uses: freckle/action-gh-release@v2
        with:
          id: ${{ needs.create-release.outputs.release_id }}
          files: "*-${{ matrix.suffix }}.tar.gz"
          fail_on_unmatched_files: true

  publish-release:
    needs:
      - create-release
      - upload-assets
    runs-on: ubuntu-latest
    steps:
      - uses: freckle/action-gh-release@v2
        with:
          id: ${{ needs.create-release.outputs.release_id }}
          draft: false
