name: Release executables

on:
  push:
    branches: main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: tag
        uses: freckle/haskell-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

  create-release:
    needs: [tag]
    if: needs.tag.outputs.tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.tag.outputs.tag }}
          release_name: Release ${{ needs.tag.outputs.tag }}
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}

  upload-assets:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            suffix: x86_64-linux
          # - os: macOS-latest
          #   suffix: x86_64-osx

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: freckle/stack-cache-action@v1
      - run: |
          mkdir -p dist/stack-lint-extra-deps
          stack build --copy-bins --local-bin-path dist/stack-lint-extra-deps
          cd dist && tar -czf ./stack-lint-extra-deps.tar.gz ./stack-lint-extra-deps
      - uses: actions/upload-release-asset@v1
        id: upload-release-asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./dist/stack-lint-extra-deps.tar.gz
          asset_name: stack-lint-extra-deps-${{ matrix.suffix }}.tar.gz
          asset_content_type: application/gzip
